remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Sheik Sadi Rohmotullah
description: Electrical and Electronics Engineer with 2 years Back-end Python development experience. Proven ability to develop robust and scalable software. Expertise in MongoDB, ElasticSearch, FastAPI, GCP, and NLP. Experience in recommender systems, data pipelines, and machine learning.
show_downloads: false
