remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Sheik Sadi Rohmotullah
description: Software Engineer specialized in Back-end development with Python. 3 years of professional experience in building robust and scalable software. Expertise in FastAPI, MongoDB, ElasticSearch, GCP, LangChain and NLP. Experience in recommender systems, data pipelines, machine learning and generative AI.
show_downloads: false
